name: Deploy Portfolio

on:
  push:
    branches:
      - main  # Triggers when you push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build the site
        run: |
          # Run your build commands, e.g., npm install && npm run build
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Update this to your build output folder
